apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: delivery
        image: delivery:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  type: NodePort
  selector:
    app: delivery
  ports:
    - protocol: TCP
      port: 8080
      name: grpc
      targetPort: 8080
      nodePort: 31400
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
      nodePort: 30400


