apiVersion: apps/v1
kind: Deployment
metadata:
  name: renting-deployment
  labels:
    app: renting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renting
  template:
    metadata:
      labels:
        app: renting
    spec:
      containers:
      - name: renting
        image: renting:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: AUTH_SERVICE_URL
          value: auth-service
        - name: DELIVERY_SERVICE_URL
          value: delivery-service
        - name: PAYMENT_SERVICE_URL
          value: payment-service
        - name: CUSTOMER_SERVICE_URL
          value: customer-service
        - name: MONGODB_URL
          value: mongodb-service
        - name: MONGODB_USER
          value: root
        - name: MONGODB_PASSWORD
          value: "123"
        - name: MONGODB_DATABASE
          value: reconcip
---
apiVersion: v1
kind: Service
metadata:
  name: renting-service
spec:
  type: NodePort
  selector:
    app: renting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30600

