apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: microservices
build:
  artifacts:
  - image: auth
    context: auth
    docker:
      dockerfile: Dockerfile
  - image: customer
    context: customer
    docker:
      dockerfile: Dockerfile
  - image: supplier
    context: supplier
    docker:
      dockerfile: Dockerfile
  - image: inventory
    context: inventory
    docker:
      dockerfile: Dockerfile
  - image: delivery
    context: delivery
    docker:
      dockerfile: Dockerfile
  - image: payment
    context: payment
    docker:
      dockerfile: Dockerfile
  - image: renting
    context: renting
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - auth.yml
  - customer.yml
  - mongodb.yml
  - supplier.yml
  - inventory.yml
  - delivery.yml
  - payment.yml
  - renting.yml
